[project.1]
Title = "Vagabonding (WIP)"
Description = "Topdown 2D Survivalite game about being a vagabond somewhere early 1900. Based on a book mentioned by Art of manliness"
Phase = 1
[project.1.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Advanced"

[project.2]
Title = "2 layer mecha battle (WIP)"
Description = "Multiplayer shooter/ Fighting game that happens in two layers. Micro is a shooter where soldiers shot enemies, repair their walker and board the enemy walker to do damage. Macro is a brawler, where the commanding crew control the walker to input CQC commands and coordinate assault teams."
Phase = 1
[project.2.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Impossible"

[project.3]
Title = " Act Raiser like (WIP)"
Description = "A 2D hack and slash/city builder where you are the avatar of a god to a monotheistic themed church. The theme is gothic metal. ressources used for city building are gold, goats and younglings. A stronger city also makes the avatar stronger. Defense missions, Escort missions, quests, etc. the map splits of into a star shape of different regions that need to be conquered."
[project.3.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Hard"

[project.4]
Title = "Perspective in beauty (WIP)"
Description = "A curated platform to share beauty. Buying digital art, information about the artists, galleries, etc."
[project.4.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Advanced"

[project.5]
Title = "Habbit Cards"
Description = "Habbit forming app that has a deck of cards for doing things like taking a walk and getting hydrated. drawing a hand multiple times during the day."
[project.5.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Advanced"

[project.6]
Title = "Eternal Desert (WIP)"
Description = "Game about Fighting and transporting nomads in a world where there is barely any metal left and a lot is carbon based. Vehicles are huge cats, dogs and similar creatures we now as pets, but they are moresomesort of cybernetic than organic, run with a yellow liquid instead of blood, etc. Clothing and art is oriented on the african desert."
[project.6.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Insane"

[project.7]
Title = "Walker Sim (WIP)"
Description = "Simple game controlling a rust bucket walker, navigating the landscape and firing artilery at targets. The walker controlls are split up and the MC has to physicially walk between controls. Walking itself happens through instructions to the pilot."
[project.7.Steps]
1 = "Fleshing out the concept"
Remaining = "~3"
Financed = 0
FinanceLimit = 10
Scope = "Beginner"
