[rust-wasm]
Description = "Figure out rust wasm"

[payment-processors]
Description = "connect to kofi etc. track donations to what they were for"

[daily-standup-youtube]
Description = "Set up a new channel"
